# Generated by Django 5.2 on 2025-05-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teplo', '0002_alter_price_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FromForm',
            new_name='Order',
        ),
    ]
